ou_email_mapping = {
    "Retail/CPG": [],
    "FSI": [],
    "MFG": [],
    "HLS": [],
    "SDP": [],
    "West/Midwest": ["pablosal@microsoft.com"],
    "South": [],
    "Northeast": [],
    "Southeast": [],
    "LATAM": [],
    "Canada": [],
    "Education": [],
    "Fed / Public Sector": [],
}